name: NodeJS with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/

    - name: Build 
      run: |
        npm install
        gulp release

    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        file: "apps/*.tar.gz;apps/*.zip"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
        draft: false
        prerelease: true
        tags: false
