name: NodeJS with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
#         registry-url: https://npm.pkg.github.com/

    - name: Build 
      run: |
        rm -f package-lock.json yarn.lock
        sed -i 's@/node_modules/marked/lib/marked.js@/node_modules/marked/marked.min.js@g' gulpfile.js
        sed -i 's@/node_modules/inflection/inflection.min.js@/node_modules/inflection/lib/inflection.js@g' gulpfile.js
        # npx yarn-upgrade-all
        yarn
        yarn upgrade --latest
        yarn gulp release

    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        file: "apps/*.tar.gz;apps/*.zip"
        overwrite: true
        verbose: false
        draft: false
        prerelease: false
        update_latest_release: true
        tags: false
        tag_name: master
