name: NodeJS with Gulp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest # windows-latest ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/

    - name: Build 
      run: |
        yarn
        yarn upgrade --latest
        yarn gulp release

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
#         tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref.name }}
        body: |
          Build for use.
        draft: false
        prerelease: false

    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        file: "apps/*.tar.gz;apps/*.zip"
        delete_file: "apps/*.tar.gz;apps/*.zip"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
